import Title from "../components/title";
import Head from "next/head";

function About() {
  return (
    <div id='about-us'>
      <Head>
        <title>About Us</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title />
    </div>
  );
}

export default About;
