//import { PrismaClient } from "@prisma/client";
import Title from "../components/title";
import Head from "next/head";

//const prisma = new PrismaClient();
//TODO: figure out how to get submitted values from new-listing.tsx
function Confirmation() {
  return (
    <div>
      <Head>
        <title>Confirmation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Title />
        <h2>Thank you! Your vehicle has been submitted</h2>
      </main>
    </div>
  );
}

export default Confirmation;
