import { PrismaClient } from "@prisma/client";
import Title from "../components/title";
import Head from "next/head";

const prisma = new PrismaClient();

async function Confirmation() {
  return (
    <div className=''>
      <Head>
        <title>Confirmation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Title />
        <h2>Thank you! Your vehicle has been submitted</h2>
      </main>
      <aside>
        <h2>Recently Sold</h2>
        <div className='recently-sold'></div>
      </aside>
    </div>
  );
}

export default Confirmation;
