import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Title from "../components/title";
import Head from "next/head";
import styles from "/styles/contact.module.scss";

function Contact() {
  return (
    <div id={styles.contact_us}>
      <Head>
        <title>Contact</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Title />
        <div id={styles.flex_container}>
          <div id={styles.form_container}>
            <h2>Send us a Message</h2>
            <form id={styles.contact_form}>
              <div className={styles.input_wrapper}>
                <label htmlFor='name'>
                  <FontAwesomeIcon icon={["fas", "user-circle"]} />
                </label>
                <input
                  id='name'
                  type='text'
                  name='name'
                  placeholder='Your name'
                  required
                />
              </div>
              <div className={styles.input_wrapper}>
                <label htmlFor='phone'>
                  <FontAwesomeIcon icon={["fas", "phone-square-alt"]} />
                </label>
                <input
                  id='phone'
                  type='tel'
                  name='phone'
                  pattern='[0-9]{3}-[0-9]{3}-[0-9]{4}'
                  placeholder='Phone'
                  required
                />
              </div>
              <div className={styles.input_wrapper}>
                <label htmlFor='email'>
                  <FontAwesomeIcon icon={["fas", "envelope"]} />
                </label>
                <input
                  id='email'
                  type='email'
                  name='email'
                  placeholder='Email'
                  required
                />
              </div>
              <div className={styles.input_wrapper}>
                <label htmlFor='message'>
                  <FontAwesomeIcon icon={["fas", "comment-alt"]} />
                </label>
                <textarea
                  id='message'
                  name='message'
                  placeholder='Message'
                  required
                />
              </div>
              <button id={styles.send_btn} type='submit'>
                Send
              </button>
            </form>
          </div>
          <div id={styles.info_container}>
            <h2>Contact Information</h2>
            <div id={styles.contact_info}>
              <div className={styles.info_wrapper}>
                <FontAwesomeIcon icon={["fas", "map-marker-alt"]} />
                <div>
                  <pre>3712 Anderson Rd </pre>
                  <pre>Coral Gables FL 33134</pre>
                </div>
              </div>
              <div className={styles.info_wrapper}>
                <FontAwesomeIcon icon={["fas", "phone-square-alt"]} />
                <div>
                  <pre>305-335-0473</pre>
                </div>
              </div>
              <div className={styles.info_wrapper}>
                <FontAwesomeIcon icon={["fas", "envelope"]} />
                <div>vb_2.0@pm.me</div>
              </div>
              <div className={styles.social_links_contact}>
                <a
                  href='https://www.facebook.com'
                  target='_blank'
                  rel='noreferrer'>
                  <FontAwesomeIcon icon={["fab", "facebook"]} />
                </a>
                <a
                  href='https://www.twitter.com'
                  target='_blank'
                  rel='noreferrer'>
                  <FontAwesomeIcon icon={["fab", "twitter"]} />
                </a>
                <a
                  href='https://www.instagram.com'
                  target='_blank'
                  rel='noreferrer'>
                  <FontAwesomeIcon icon={["fab", "instagram"]} />
                </a>
                <a
                  href='https://www.youtube.com'
                  target='_blank'
                  rel='noreferrer'>
                  <FontAwesomeIcon icon={["fab", "youtube"]} />
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Contact;
