import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { PrismaClient } from "@prisma/client";
import Image from "next/image";

/**
 * This is a home page.
 * @returns {JSX.Element}: The JSX Code for Home Page.
 */

export default function Home({ vehicles }): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Car Auctions</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h2>Featured Auctions</h2>
        <div>
          {vehicles.map((vehicle, i) => {
            return (
              <div key={i} className={styles.listing}>
                <Image
                  style={{ opacity: 0.5 }}
                  src='/images/background.jpg'
                  alt='main picture'
                  width={350}
                  height={217}></Image>
                <div className={styles.info}>
                  <h2>
                    {vehicle.year} {vehicle.make} {vehicle.model}
                  </h2>
                  <p>{vehicle.description}</p>
                  <button>read more</button>
                </div>
              </div>
            );
          })}
        </div>
      </main>
      <aside>
        <h2>Current Auctions</h2>
        <div className='current_auctions'></div>
      </aside>
    </div>
  );
}

export async function getServerSideProps() {
  const prisma = new PrismaClient();
  const vehicles = await prisma.vehicle.findMany();
  return { props: { vehicles } };
}
