import Head from "next/head";
import styles from "../styles/Home.module.css";
import Title from "../components/title";

/**
 * This is a home page.
 * @returns {JSX.Element}: The JSX Code for Home Page.
 */

export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Car Auctions</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Title />
      </main>
    </div>
  );
}
