import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Title from "../components/title";
import Head from "next/head";

function Register() {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session) router.push("/dash");
  });

  return <>
    <div id='register'>
      <Head>
        <title>Register</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title />
      <form id='register-form' method='POST' action='api/register-form'>
        <h2>Create an account</h2>
        <h3>All fields are required</h3>
        <div id='form-wrapper'>
          <div className='field-wrapper'>
            <label htmlFor='fname'>
              <FontAwesomeIcon icon={["fas", "user-circle"]} />
            </label>
            <input
              type='text'
              id='fname'
              name='firstname'
              placeholder='First Name'
              required
            />
          </div>
          <div className='field-wrapper'>
            <label htmlFor='lname'>
              <FontAwesomeIcon icon={["fas", "user-circle"]} />
            </label>
            <input
              type='text'
              id='lname'
              name='lastname'
              placeholder='Last Name'
              required
            />
          </div>
          <div className='field-wrapper'>
            <label htmlFor='email'>
              <FontAwesomeIcon icon={["fas", "envelope"]} />
            </label>
            <input
              type='text'
              id='email'
              name='email'
              placeholder='Email'
              required
            />
          </div>
          <div className='field-wrapper'>
            <label htmlFor='password'>
              <FontAwesomeIcon icon={["fas", "lock"]} />
            </label>
            <input
              type='password'
              id='password'
              name='password'
              placeholder='Password'
              required
            />
          </div>
          <div className='field-wrapper'>
            <label htmlFor='confirm-psw'>
              <FontAwesomeIcon icon={["fas", "lock"]} />
            </label>
            <input
              type='password'
              id='confirm-psw'
              name='confirm-psw'
              placeholder='Confirm Password'
              required
            />
          </div>
          <button
            form='register-form'
            id='register-btn'
            type='submit'
            formMethod='post'
            formAction='/api/register-form'>
            Register
          </button>
        </div>
      </form>
      <div id='login-here'>
        Already have an account? | Please{" "}
        <Link href='/api/auth/signin' legacyBehavior>login here</Link>
      </div>
    </div>
    <style jsx>{`
      #register {
        display: flex;
        flex-flow: column wrap;
        align-items: center;

        #register-header {
          text-align: left;
          margin: 0 0 150px;
          width: 90%;
        }

        #register-form {
          background: #fff;
          width: 75%;
          margin: 0 auto 50px;

          h2 {
            padding: 20px 30px;
            text-transform: uppercase;
            background: rgb(49, 110, 223);
            width: 100%;
            color: #fff;
            text-align: left;
          }

          h3 {
            font-weight: normal;
            padding: 20px 30px;
            width: 100%;
            text-align: left;
          }

          #form-wrapper {
            display: flex;
            flex-flow: row wrap;
            justify-content: space-between;
            padding: 0 30px 40px;

            .field-wrapper {
              display: flex;
              flex-flow: row nowrap;
              background: rgb(0, 85, 72);
              margin-bottom: 30px;
              width: 100%;
              position: relative;

              &:nth-child(1),
              &:nth-child(2),
              &:nth-child(4),
              &:nth-child(5) {
                width: 48%;

                @media only screen and (max-width: 440px) {
                  width: 100%;
                }
              }
            }

            #register-btn {
              margin: auto;
              width: 50%;
              line-height: 2.5em;
              font-weight: bold;
              text-transform: uppercase;
              background: rgb(0, 211, 148);
              border: none;
              cursor: pointer;
              transition: background-color 0.5s, color 0.5s;

              &:hover {
                background: rgb(49, 110, 223);
                color: rgb(157, 255, 214);
              }

              @media only screen and (max-width: 440px) {
                width: 100%;
              }
            }
          }

          label {
            background: rgb(0, 59, 50);
            line-height: 2em;
            font-size: 1.5em;
            color: #fff;
            width: 40px;
          }

          input {
            font-size: 1.5em;
            color: #fff;
            line-height: 2em;
            padding: 0 10px;
            border: none;
            background: transparent;
            width: 100%;

            &::placeholder {
              color: #fff;
              opacity: 0.8;
            }
          }

          @media only screen and (max-width: 730px) {
            width: 90%;
          }
        }
      }
    `}</style>
  </>;
}

export default Register;
