import Head from "next/head";
import Title from "../components/title";

function Reset() {
  return (
    <div id='reset'>
      <Head>
        <title>Password Reset</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title />
    </div>
  );
}

export default Reset;
